name: main integration build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: '1.23.2'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Run coverage
      run: go test ./... -coverpkg "$(go list || go list -m | head -1)/..." -coverprofile coverage-raw.out -p 1

    - name: Clean coverage
      run: cat coverage-raw.out | grep -vE 'mock|test|file.go' > coverage.out

    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0.3.1
      with:
        coverage-file: coverage.out
        report: true
        chart: true
        amend: true
      if: github.event_name == 'push'
      continue-on-error: true
